[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dataweave-native"
version = "0.0.1"
description = "Python bindings for the DataWeave native library"
requires-python = ">=3.9"

[project.optional-dependencies]
test = ["pytest", "pytest-cov"]
