[metadata]
name = dataweave-native
version = 0.0.1
description = Python bindings for the DataWeave native library
long_description = file: README.md
long_description_content_type = text/markdown
url = https://dataweave.mulesoft.com/
author = MuleSoft
license = BSD-3-Clause
license_files = ../../LICENSE.txt
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    License :: OSI Approved :: BSD License
project_urls =
    Source = https://github.com/mulesoft/data-weave-cli
    Issues = https://github.com/mulesoft/data-weave-cli/issues
    Documentation = https://github.com/mulesoft/data-weave-cli/tree/master/native-lib/python

[options]
package_dir =
    = src
packages = find:
include_package_data = True
python_requires = >=3.9

[options.packages.find]
where = src

[options.extras_require]
test =
    pytest
    pytest-cov

[options.package_data]
dataweave =
    native/*
