name: CI Native CLI

on:
  schedule:
    - cron: '0 12 * * 3' # This runs the workflow every wednesday day at 12:00 UTC
env:
  NATIVE_VERSION: 100.100.100

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  CI:
    strategy:
      matrix:
        os: [ mulesoft-ubuntu, mulesoft-windows ]
        include:
          - os: mulesoft-ubuntu
            script_name: linux
          - os: mulesoft-windows
            script_name: windows
    runs-on: ${{ matrix.os }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # Setup Graalvm
      - name: Setup Graalvm
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '24'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Runs a single command using the runners shell
      - name: Run Build (Latest)
        run: |
          ./gradlew --stacktrace --no-problems-report -PweaveVersion=2.11.0-SNAPSHOT -PweaveTestSuiteVersion=2.11.0-SNAPSHOT -PweaveSuiteVersion=2.11.0-SNAPSHOT build
        shell: bash

      # Generate distro
      - name: Create Distro
        run: ./gradlew --stacktrace --no-problems-report -PweaveVersion=2.11.0-SNAPSHOT -PweaveTestSuiteVersion=2.11.0-SNAPSHOT -PweaveSuiteVersion=2.11.0-SNAPSHOT native-cli:distro
        shell: bash

      # Upload the artifact file
      - name: Upload generated script
        uses: actions/upload-artifact@v4
        with:
          name: dw-${{env.NATIVE_VERSION}}-${{runner.os}}
          path: native-cli/build/distributions/native-cli-${{env.NATIVE_VERSION}}-native-distro-${{ matrix.script_name }}.zip
